# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rating_engine}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adrian Cuadros"]
  s.date = %q{2010-07-26}
  s.description = %q{Attempts to take advantage of the acts_as_rateable plugin and make it unobstrusive and flexible using Rails 3 Engines.}
  s.email = %q{adrian@innku.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "app/controllers/ratings_controller.rb",
     "app/models/rate.rb",
     "app/models/rating.rb",
     "lib/generators/rating_engine/install/install_generator.rb",
     "lib/generators/rating_engine/install/templates/README",
     "lib/generators/rating_engine/install/templates/migrate/create_rates.rb",
     "lib/generators/rating_engine/install/templates/migrate/create_ratings.rb",
     "lib/rating_engine.rb",
     "lib/rating_engine/acts_as_rateable.rb",
     "lib/rating_engine/engine.rb",
     "pkg/Rateable Engine-0.0.0.gem",
     "pkg/rating_engine-0.0.0.gem",
     "rating_engine.gemspec",
     "test/acts_as_rateable_test.rb"
  ]
  s.homepage = %q{http://github.com/adriancuadros/acts_as_rateable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Fork of acts_as_rateable plugin. Ratings as an engine.}
  s.test_files = [
    "test/acts_as_rateable_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

