# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rating_engine}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adrian Cuadros"]
  s.date = %q{2010-07-29}
  s.description = %q{Attempts to take advantage of the acts_as_rateable plugin and make it unobstrusive and flexible using Rails 3 Engines.}
  s.email = %q{adrian@innku.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "app/controllers/rating_engine/ratings_controller.rb",
     "app/helpers/rating_engine/ratings_helper.rb",
     "app/models/rating_engine/rate.rb",
     "app/models/rating_engine/rating.rb",
     "app/observers/rating_engine/rating_observer.rb",
     "app/views/rating_engine/ratings/_star_rating.html.erb",
     "lib/generators/rating_engine/install/install_generator.rb",
     "lib/generators/rating_engine/install/templates/README",
     "lib/generators/rating_engine/install/templates/images/star_sprite.gif",
     "lib/generators/rating_engine/install/templates/initializers/rating_engine.rb",
     "lib/generators/rating_engine/install/templates/javascripts/rating_engine.jquery.js",
     "lib/generators/rating_engine/install/templates/migrate/create_rates.rb",
     "lib/generators/rating_engine/install/templates/migrate/create_ratings.rb",
     "lib/generators/rating_engine/install/templates/stylesheets/star_rating.css",
     "lib/generators/rating_engine/views/views_generator.rb",
     "lib/rating_engine.rb",
     "lib/rating_engine/acts_as_rateable.rb",
     "lib/rating_engine/configuration_helper.rb",
     "lib/rating_engine/engine.rb",
     "lib/rating_engine/routes.rb",
     "pkg/rating_engine-0.0.0.gem",
     "rating_engine.gemspec",
     "test/factories.rb",
     "test/helper.rb",
     "test/integration/test_ratings.rb",
     "test/models/test_rating.rb",
     "test/support/assertions.rb",
     "test/support/helpers.rb",
     "test/support/rating_engine_helpers.rb",
     "test/test_app/.gitignore",
     "test/test_app/Gemfile",
     "test/test_app/Gemfile.lock",
     "test/test_app/README",
     "test/test_app/Rakefile",
     "test/test_app/app/controllers/application_controller.rb",
     "test/test_app/app/controllers/products_controller.rb",
     "test/test_app/app/controllers/users_controller.rb",
     "test/test_app/app/helpers/application_helper.rb",
     "test/test_app/app/helpers/products_helper.rb",
     "test/test_app/app/helpers/users_helper.rb",
     "test/test_app/app/models/product.rb",
     "test/test_app/app/models/user.rb",
     "test/test_app/app/views/layouts/application.html.erb",
     "test/test_app/app/views/products/_form.html.erb",
     "test/test_app/app/views/products/edit.html.erb",
     "test/test_app/app/views/products/index.html.erb",
     "test/test_app/app/views/products/new.html.erb",
     "test/test_app/app/views/products/show.html.erb",
     "test/test_app/app/views/users/_form.html.erb",
     "test/test_app/app/views/users/edit.html.erb",
     "test/test_app/app/views/users/index.html.erb",
     "test/test_app/app/views/users/new.html.erb",
     "test/test_app/app/views/users/show.html.erb",
     "test/test_app/config.ru",
     "test/test_app/config/application.rb",
     "test/test_app/config/boot.rb",
     "test/test_app/config/database.yml",
     "test/test_app/config/environment.rb",
     "test/test_app/config/environments/development.rb",
     "test/test_app/config/environments/production.rb",
     "test/test_app/config/environments/test.rb",
     "test/test_app/config/initializers/backtrace_silencers.rb",
     "test/test_app/config/initializers/inflections.rb",
     "test/test_app/config/initializers/mime_types.rb",
     "test/test_app/config/initializers/rating_engine.rb",
     "test/test_app/config/initializers/secret_token.rb",
     "test/test_app/config/initializers/session_store.rb",
     "test/test_app/config/locales/en.yml",
     "test/test_app/config/routes.rb",
     "test/test_app/db/migrate/20100728153200_create_users.rb",
     "test/test_app/db/migrate/20100728153233_create_products.rb",
     "test/test_app/db/migrate/20100728154559_create_rates.rb",
     "test/test_app/db/migrate/20100728154560_create_ratings.rb",
     "test/test_app/db/schema.rb",
     "test/test_app/db/seeds.rb",
     "test/test_app/doc/README_FOR_APP",
     "test/test_app/lib/tasks/.gitkeep",
     "test/test_app/public/404.html",
     "test/test_app/public/422.html",
     "test/test_app/public/500.html",
     "test/test_app/public/favicon.ico",
     "test/test_app/public/images/rails.png",
     "test/test_app/public/images/star_sprite.gif",
     "test/test_app/public/index.html",
     "test/test_app/public/javascripts/application.js",
     "test/test_app/public/javascripts/jquery.js",
     "test/test_app/public/robots.txt",
     "test/test_app/public/stylesheets/.gitkeep",
     "test/test_app/public/stylesheets/scaffold.css",
     "test/test_app/public/stylesheets/star_rating.css",
     "test/test_app/script/rails",
     "test/test_app/vendor/plugins/.gitkeep"
  ]
  s.homepage = %q{http://github.com/adriancuadros/acts_as_rateable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Fork of acts_as_rateable plugin. Ratings as an engine.}
  s.test_files = [
    "test/factories.rb",
     "test/helper.rb",
     "test/integration/test_ratings.rb",
     "test/models/test_rating.rb",
     "test/support/assertions.rb",
     "test/support/helpers.rb",
     "test/support/rating_engine_helpers.rb",
     "test/test_app/app/controllers/application_controller.rb",
     "test/test_app/app/controllers/products_controller.rb",
     "test/test_app/app/controllers/users_controller.rb",
     "test/test_app/app/helpers/application_helper.rb",
     "test/test_app/app/helpers/products_helper.rb",
     "test/test_app/app/helpers/users_helper.rb",
     "test/test_app/app/models/product.rb",
     "test/test_app/app/models/user.rb",
     "test/test_app/config/application.rb",
     "test/test_app/config/boot.rb",
     "test/test_app/config/environment.rb",
     "test/test_app/config/environments/development.rb",
     "test/test_app/config/environments/production.rb",
     "test/test_app/config/environments/test.rb",
     "test/test_app/config/initializers/backtrace_silencers.rb",
     "test/test_app/config/initializers/inflections.rb",
     "test/test_app/config/initializers/mime_types.rb",
     "test/test_app/config/initializers/rating_engine.rb",
     "test/test_app/config/initializers/secret_token.rb",
     "test/test_app/config/initializers/session_store.rb",
     "test/test_app/config/routes.rb",
     "test/test_app/db/migrate/20100728153200_create_users.rb",
     "test/test_app/db/migrate/20100728153233_create_products.rb",
     "test/test_app/db/migrate/20100728154559_create_rates.rb",
     "test/test_app/db/migrate/20100728154560_create_ratings.rb",
     "test/test_app/db/schema.rb",
     "test/test_app/db/seeds.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

